services:
  remnawave-prometheus:
    image: hteppl/remnawave-prometheus:latest
    container_name: remnawave-prometheus
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./generated:/app/generated
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"